/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetStationsResponse: core.serialization.ObjectSchema<serializers.GetStationsResponse.Raw, BumpshApi.GetStationsResponse>;
export declare namespace GetStationsResponse {
    interface Raw {
        data?: serializers.Station.Raw[] | null;
        links?: serializers.GetStationsResponseLinks.Raw | null;
    }
}
