/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetStationsResponseLinks: core.serialization.ObjectSchema<serializers.GetStationsResponseLinks.Raw, BumpshApi.GetStationsResponseLinks>;
export declare namespace GetStationsResponseLinks {
    interface Raw extends serializers.LinksSelf.Raw, serializers.LinksPagination.Raw {
    }
}
