/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BumpshApi from "../../../index";
export interface GetStationsResponse {
    data?: BumpshApi.Station[];
    links?: BumpshApi.GetStationsResponseLinks;
}
