trigger:
  branches:
    include:
      - '*'

variables: 
- group: bumpsh

pool:
  vmImage: 'ubuntu-latest'
  demands: 
    - npm

jobs:
  - job: validate_doc
    # Only run this task if build was triggered by a commit to a branch other than main
    condition: and(succeeded(), ne(variables['build.sourceBranch'], 'refs/heads/main'))
    steps:
      - script: npx bump-cli deploy --dry-run "openapi.yaml" --doc "azure-demo" --token="$BUMP_TOKEN"
        displayName: 'Validate API'

  - job: deploy_doc
    # Only run this task if build was triggered by a commit to the main branch
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    steps:
      - script: |
          npx bump-cli deploy "openapi.yaml" --doc "azure-demo" --token="$BUMP_TOKEN"
        displayName: 'Deploy API Documentation'
