# Trigger pipeline on pushes to main branch
trigger:
- main

variables: 
- group: bumpsh

pool:
  vmImage: 'ubuntu-latest'

steps:
- displayName: 'Install Node.js'
  task: UseNode@1
  inputs:
    version: '20.x'

- displayName: 'Install Bump CLI'
  bash: |
    npm install bump-cli

- displayName: 'Deploy API Documentation'
  bash: |
    npm exec -- bump deploy "openapi.yaml" --doc "azure-demo" --token "$(BUMP_TOKEN)"
