trigger:
  branches:
    include:
      - '*'

variables: 
- group: bumpsh

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: validate_doc
    # Only run this task if build was triggered by a commit to a branch other than main
    condition: and(succeeded(), ne(variables['build.sourceBranch'], 'refs/heads/main'))
    steps:
      - script: npx bump-cli deploy --dry-run "openapi.yaml" --doc "azure-demo"
        displayName: 'Validate API'

  - job: deploy_doc
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    steps:
      # Only run this task if build was triggered by a commit to the main branch
      - script: |
          npx bump-cli deploy "openapi.yaml" --doc "azure-demo"
        displayName: 'Deploy API Documentation'

  - job: diff_doc
    steps:
      - task: PullRequestComment@1
        # Only run this task if the build was triggered by a pull request 
        inputs:
          active: false
          comment: |
            This is **sample** _text_ 🎉
            [This is link](https://microsoft.com)
            Build ID is $(Build.BuildId)
            | Table |
            |---|
            | Cell |
        displayName: 'PR Comment'
