trigger:
  branches:
    include:
      - '*'

variables: 
- group: bumpsh
- name: BUMP_ID
  value: azure-demo

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Setup
  jobs:
  - job: installDependencies
    steps:
    - task: UseNode@1
      inputs:
        version: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install bump-cli
      displayName: 'Install Bump CLI'

- stage: DeployDocs
  dependsOn: Setup
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: deploy_doc
    steps:
      # Only run this task if the build is successful and the build was triggered by a commit to the main branch
      - script: |
          npm exec -- bump deploy "openapi.yaml" --doc "$BUMP_ID"
        displayName: 'Deploy API Documentation'

- stage: CheckChanges
  dependsOn: Setup
  condition: and(succeeded(), ne(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: validate_doc
    steps:
      - script: npm exec -- bump deploy --dry-run "openapi.yaml" --doc "$BUMP_ID" 
        displayName: 'Test API'

  - job: diff_doc
    steps:
      - task: PullRequestComment@1
        # Only run this task if the build is successful and the build was triggered by a pull request
        condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
        inputs:
          active: false
          comment: |
            This is **sample** _text_ 🎉
            [This is link](https://microsoft.com)
            Build ID is $(Build.BuildId)
            | Table |
            |---|
            | Cell |
        displayName: 'PR Comment'
