# Trigger pipeline on pushes to main branch
trigger:
- main

# Specify the agent pool to use (Ubuntu)
pool:
  vmImage: 'ubuntu-latest'

variables: 
  - group: bumpsh

# Define pipeline steps
steps:
  
  # Install Node.js using UseNode task
  - task: UseNode@1
    inputs:
      version: '20.x'

  - bash: |
      npm install bump-cli

  - bash: |
      npm exec -- bump deploy "openapi.yaml" --doc "azure-demo" --token "$(BUMP_TOKEN)"
