# Trigger pipeline on pushes to main branch
trigger:
- main

variables: 
- group: bumpsh

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- bash: |
    npm install bump-cli
  displayName: 'Install Bump CLI'

- bash: |
    npm exec -- bump deploy "openapi.yaml" --doc "azure-demo" --token "$(BUMP_TOKEN)"
  displayName: 'Deploy API Documentation'
