/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BumpshApi from "../../../index";
export interface GetBookingResponse extends BumpshApi.Booking {
    links?: BumpshApi.LinksSelf;
}
