/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BumpshApi from "../../../index";
export interface NewBookingPayload extends BumpshApi.Booking {
    links?: BumpshApi.NewBookingPayloadLinks;
}
