/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BumpshApi from "../../../index";
export interface GetTripsResponseLinks extends BumpshApi.LinksSelf, BumpshApi.LinksPagination {
}
