/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BumpshApi from "../../../index";
export interface CreateBookingPaymentResponse extends BumpshApi.BookingPayment {
    links?: BumpshApi.LinksBooking;
}
