/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const Booking: core.serialization.ObjectSchema<serializers.Booking.Raw, BumpshApi.Booking>;
export declare namespace Booking {
    interface Raw {
        id?: string | null;
        trip_id?: string | null;
        passenger_name?: string | null;
        has_bicycle?: boolean | null;
        has_dog?: boolean | null;
    }
}
