/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const BookingPaymentSourceBankAccountAccountType: core.serialization.Schema<serializers.BookingPaymentSourceBankAccountAccountType.Raw, BumpshApi.BookingPaymentSourceBankAccountAccountType>;
export declare namespace BookingPaymentSourceBankAccountAccountType {
    type Raw = "individual" | "company";
}
