/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const BookingPaymentStatus: core.serialization.Schema<serializers.BookingPaymentStatus.Raw, BumpshApi.BookingPaymentStatus>;
export declare namespace BookingPaymentStatus {
    type Raw = "pending" | "succeeded" | "failed";
}
