/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const BookingPayment: core.serialization.ObjectSchema<serializers.BookingPayment.Raw, BumpshApi.BookingPayment>;
export declare namespace BookingPayment {
    interface Raw {
        id?: string | null;
        amount?: number | null;
        currency?: serializers.BookingPaymentCurrency.Raw | null;
        source?: serializers.BookingPaymentSource.Raw | null;
        status?: serializers.BookingPaymentStatus.Raw | null;
    }
}
