/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const BookingPaymentSourceBankAccount: core.serialization.ObjectSchema<serializers.BookingPaymentSourceBankAccount.Raw, BumpshApi.BookingPaymentSourceBankAccount>;
export declare namespace BookingPaymentSourceBankAccount {
    interface Raw {
        name: string;
        number: string;
        sort_code?: string | null;
        account_type: serializers.BookingPaymentSourceBankAccountAccountType.Raw;
        bank_name: string;
        country: string;
    }
}
