/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const BookingPaymentCurrency: core.serialization.Schema<serializers.BookingPaymentCurrency.Raw, BumpshApi.BookingPaymentCurrency>;
export declare namespace BookingPaymentCurrency {
    type Raw = "bam" | "bgn" | "chf" | "eur" | "gbp" | "nok" | "sek" | "try";
}
