/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const BookingPaymentSource: core.serialization.Schema<serializers.BookingPaymentSource.Raw, BumpshApi.BookingPaymentSource>;
export declare namespace BookingPaymentSource {
    type Raw = BookingPaymentSource.Card | BookingPaymentSource.BankAccount;
    interface Card extends serializers.Card.Raw {
        object: "card";
    }
    interface BankAccount extends serializers.BookingPaymentSourceBankAccount.Raw {
        object: "bank_account";
    }
}
