/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const Card: core.serialization.ObjectSchema<serializers.Card.Raw, BumpshApi.Card>;
export declare namespace Card {
    interface Raw {
        name: string;
        number: string;
        cvc: number;
        exp_month: number;
        exp_year: number;
        address_line1?: string | null;
        address_line2?: string | null;
        address_city?: string | null;
        address_country: string;
        address_post_code?: string | null;
    }
}
