/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const LinksBooking: core.serialization.ObjectSchema<serializers.LinksBooking.Raw, BumpshApi.LinksBooking>;
export declare namespace LinksBooking {
    interface Raw {
        booking?: string | null;
    }
}
