/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const OauthScope: core.serialization.Schema<serializers.OauthScope.Raw, BumpshApi.OauthScope>;
export declare namespace OauthScope {
    type Raw = "read" | "write";
}
