/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as BumpshApi from "../../api/index";
import * as core from "../../core";
export declare const Station: core.serialization.ObjectSchema<serializers.Station.Raw, BumpshApi.Station>;
export declare namespace Station {
    interface Raw {
        id: string;
        name: string;
        address: string;
        country_code: string;
        timezone?: string | null;
    }
}
