name: Feedback
description: Help us improve this API with constructive feedback.
title: "[Feedback]: "
labels: ["feedback"]
assignees:
  - philsturgeon # change this to whoever should be in charge of handling feedback
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve!
  - type: textarea
    id: doing-well
    attributes:
      label: What are we doing well?
      description: Help us know where energy has been well invested so we can keep that up.
    validations:
      required: true
  - type: textarea
    id: could-improve
    attributes:
      label: What would you like to see improved?
      description: Help us learn what you'd like to see done better so we can make life easier for more users.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: "eg: email@example.com"
    validations:
      required: false
