/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const CreateBookingResponse: core.serialization.ObjectSchema<serializers.CreateBookingResponse.Raw, BumpshApi.CreateBookingResponse>;
export declare namespace CreateBookingResponse {
    interface Raw extends serializers.Booking.Raw {
        links?: serializers.LinksSelf.Raw | null;
    }
}
