/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetBookingsResponse: core.serialization.ObjectSchema<serializers.GetBookingsResponse.Raw, BumpshApi.GetBookingsResponse>;
export declare namespace GetBookingsResponse {
    interface Raw {
        data?: serializers.Booking.Raw[] | null;
        links?: serializers.GetBookingsResponseLinks.Raw | null;
    }
}
