/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetBookingsResponseLinks: core.serialization.ObjectSchema<serializers.GetBookingsResponseLinks.Raw, BumpshApi.GetBookingsResponseLinks>;
export declare namespace GetBookingsResponseLinks {
    interface Raw extends serializers.LinksSelf.Raw, serializers.LinksPagination.Raw {
    }
}
