/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const NewBookingPayload: core.serialization.ObjectSchema<serializers.NewBookingPayload.Raw, BumpshApi.NewBookingPayload>;
export declare namespace NewBookingPayload {
    interface Raw extends serializers.Booking.Raw {
        links?: serializers.NewBookingPayloadLinks.Raw | null;
    }
}
