/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Booking {
    /** Unique identifier for the booking */
    id?: string;
    /** Identifier of the booked trip */
    tripId?: string;
    /** Name of the passenger */
    passengerName?: string;
    /** Indicates whether the passenger has a bicycle. */
    hasBicycle?: boolean;
    /** Indicates whether the passenger has a dog. */
    hasDog?: boolean;
}
