/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BumpshApi from "../index";
/**
 * The payment source to take the payment from. This can be a card or a bank account. Some of these properties will be hidden on read to protect PII leaking.
 */
export declare type BookingPaymentSource = 
/**
 * A card (debit or credit) to take payment from. */
BumpshApi.BookingPaymentSource.Card
/**
 * A bank account to take payment from. Must be able to make payments in the currency specified in the payment. */
 | BumpshApi.BookingPaymentSource.BankAccount;
export declare namespace BookingPaymentSource {
    interface Card extends BumpshApi.Card {
        object: "card";
    }
    interface BankAccount extends BumpshApi.BookingPaymentSourceBankAccount {
        object: "bank_account";
    }
}
