/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as BumpshApi from "../index";
export interface BookingPayment {
    /** Unique identifier for the payment. This will be a unique identifier for the payment, and is used to reference the payment in other objects. */
    id?: string;
    /** Amount intended to be collected by this payment. A positive decimal figure describing the amount to be collected. */
    amount?: number;
    /** Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. */
    currency?: BumpshApi.BookingPaymentCurrency;
    /** The payment source to take the payment from. This can be a card or a bank account. Some of these properties will be hidden on read to protect PII leaking. */
    source?: BumpshApi.BookingPaymentSource;
    /** The status of the payment, one of `pending`, `succeeded`, or `failed`. */
    status?: BumpshApi.BookingPaymentStatus;
}
