"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookingPaymentSourceBankAccountAccountType = void 0;
exports.BookingPaymentSourceBankAccountAccountType = {
    Individual: "individual",
    Company: "company",
};
