/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The status of the payment, one of `pending`, `succeeded`, or `failed`.
 */
export declare type BookingPaymentStatus = "pending" | "succeeded" | "failed";
export declare const BookingPaymentStatus: {
    readonly Pending: "pending";
    readonly Succeeded: "succeeded";
    readonly Failed: "failed";
};
