/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of entity that holds the account. This can be either `individual` or `company`.
 */
export declare type BookingPaymentSourceBankAccountAccountType = "individual" | "company";
export declare const BookingPaymentSourceBankAccountAccountType: {
    readonly Individual: "individual";
    readonly Company: "company";
};
