/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
 */
export declare type BookingPaymentCurrency = "bam" | "bgn" | "chf" | "eur" | "gbp" | "nok" | "sek" | "try";
export declare const BookingPaymentCurrency: {
    readonly Bam: "bam";
    readonly Bgn: "bgn";
    readonly Chf: "chf";
    readonly Eur: "eur";
    readonly Gbp: "gbp";
    readonly Nok: "nok";
    readonly Sek: "sek";
    readonly Try: "try";
};
