/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A card (debit or credit) to take payment from.
 */
export interface Card {
    /** Cardholder's full name as it appears on the card. */
    name: string;
    /** The card number, as a string without any separators. On read all but the last four digits will be masked for security. */
    number: string;
    /** Card security code, 3 or 4 digits usually found on the back of the card. */
    cvc: number;
    /** Two-digit number representing the card's expiration month. */
    expMonth: number;
    /** Four-digit number representing the card's expiration year. */
    expYear: number;
    addressLine1?: string;
    addressLine2?: string;
    addressCity?: string;
    addressCountry: string;
    addressPostCode?: string;
}
