/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type OauthScope = 
/**
 * Read access */
"read"
/**
 * Write access */
 | "write";
export declare const OauthScope: {
    readonly Read: "read";
    readonly Write: "write";
};
