"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OauthScope = void 0;
exports.OauthScope = {
    Read: "read",
    Write: "write",
};
