/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Problem {
    /** A URI reference that identifies the problem type */
    type?: string;
    /** A short, human-readable summary of the problem type */
    title?: string;
    /** A human-readable explanation specific to this occurrence of the problem */
    detail?: string;
    /** A URI reference that identifies the specific occurrence of the problem */
    instance?: string;
    /** The HTTP status code */
    status?: number;
}
