/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Trip {
    /** Unique identifier for the trip */
    id?: string;
    /** The starting station of the trip */
    origin?: string;
    /** The destination station of the trip */
    destination?: string;
    /** The date and time when the trip departs */
    departureTime?: Date;
    /** The date and time when the trip arrives */
    arrivalTime?: Date;
    /** The name of the operator of the trip */
    operator?: string;
    /** The cost of the trip */
    price?: number;
    /** Indicates whether bicycles are allowed on the trip */
    bicyclesAllowed?: boolean;
    /** Indicates whether dogs are allowed on the trip */
    dogsAllowed?: boolean;
}
