/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export interface WrapperCollection {
    /** The wrapper for a collection is an array of objects. */
    data?: Record<string, unknown>[];
    /** A set of hypermedia links which serve as controls for the client. */
    links?: Record<string, unknown>;
}
