"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookingPaymentStatus = void 0;
exports.BookingPaymentStatus = {
    Pending: "pending",
    Succeeded: "succeeded",
    Failed: "failed",
};
