"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BookingPaymentCurrency = void 0;
exports.BookingPaymentCurrency = {
    Bam: "bam",
    Bgn: "bgn",
    Chf: "chf",
    Eur: "eur",
    Gbp: "gbp",
    Nok: "nok",
    Sek: "sek",
    Try: "try",
};
