/**
 * This file was auto-generated by Fern from our API Definition.
 */
import express from "express";
import { StationsService } from "./api/resources/stations/service/StationsService";
import { TripsService } from "./api/resources/trips/service/TripsService";
import { BookingsService } from "./api/resources/bookings/service/BookingsService";
import { PaymentsService } from "./api/resources/payments/service/PaymentsService";
export declare function register(expressApp: express.Express | express.Router, services: {
    stations: StationsService;
    trips: TripsService;
    bookings: BookingsService;
    payments: PaymentsService;
}): void;
