"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.register = void 0;
function register(expressApp, services) {
    expressApp.use("", services.stations.toRouter());
    expressApp.use("", services.trips.toRouter());
    expressApp.use("", services.bookings.toRouter());
    expressApp.use("", services.payments.toRouter());
}
exports.register = register;
