/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const CreateBookingPaymentResponse: core.serialization.ObjectSchema<serializers.CreateBookingPaymentResponse.Raw, BumpshApi.CreateBookingPaymentResponse>;
export declare namespace CreateBookingPaymentResponse {
    interface Raw extends serializers.BookingPayment.Raw {
        links?: serializers.LinksBooking.Raw | null;
    }
}
