/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetTripsResponseLinks: core.serialization.ObjectSchema<serializers.GetTripsResponseLinks.Raw, BumpshApi.GetTripsResponseLinks>;
export declare namespace GetTripsResponseLinks {
    interface Raw extends serializers.LinksSelf.Raw, serializers.LinksPagination.Raw {
    }
}
