/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as BumpshApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetTripsResponse: core.serialization.ObjectSchema<serializers.GetTripsResponse.Raw, BumpshApi.GetTripsResponse>;
export declare namespace GetTripsResponse {
    interface Raw {
        data?: serializers.Trip.Raw[] | null;
        links?: serializers.GetTripsResponseLinks.Raw | null;
    }
}
